name: docker ci build

on:
  push:
    branches:
      - main

jobs: 
  fastapi-ci-build:
    name: building on ubuntu latest
    runs-on: ubuntu-latest
    steps:
      - name: using actions checkout version 2
        uses: actions/checkout@v2
      - name: test 
        run: echo test
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}   
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build fastapi
        run: |
          DOCKER_BUILDKIT=1 docker build -t spkosana/fastapi:1.0 .
      - name: docker push
        run: |
          docker push spkosana/fastapi:1.0