name: docker ci build

on:
  push:
    branches:
      - main

jobs: 
  fastapi-ci-build:
    runs-on: ubuntu-latest
    steps:
    # This command 
      - uses: actions/checkout@v2  
      # - name: docker login
      #   env:
      #     DOCKER_USER: ${{ secrets.DOCKER_USER }}   
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   run: |
      #     docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      # - name: docker build fastapi
      #   run: |
      #     docker build -t spkosana/fastapi:v1 .
      # - name: docker push
      #   run: |
      #     docker push spkosana/fastapi:v1
      - name: install arkade
        run: curl -sLS https://dl.get-arkade.dev | sudo sh
      - name: check arkade installation
        run: arkade version
      - name: install kubectl using arkade
        run: | 
          arkade get kubectl
          kubectl version
      - name: install kind using arkade
        run: |
          arkade get kind
          kind version
      - name: create kind Cluster
        run: |
          kind create cluster --name fastapi --config kind-cluster.yml --wait 2m
          kubectl cluster-info --context kind-fastapi
          kubectl get nodes
          sleep 1m
          kubectl get nodes
          kubectl get all
      # - name: list fastapi yaml file
      #   run: |
      #     web-start.sh
      #     kubectl get all

      